apiVersion: v1
kind: Secret
metadata:
  name: platform-secret-newrelic-app-name
type: Opaque
data:
  NEWRELIC_APP_NAME: ENC[AES256_GCM,data:Z6S0FG8BqF1CeXpp1nLTahCGmZUCXVtrD66c7PLvkw4RJQymLtvMtA==,iv:1js3moSa22T7PmNhuzzp7k94feN0fzvF9zXRQwZTvXM=,tag:roltJsGGsYjSlmKVn87dww==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1jglwyzrn80auhq0k93mv8zqn5ezt6ngsdvhjn23nwfh0quq7wussn2tdm3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdEhkZ1RLVVVwK2Fhc2c2
        M2htM3F0Qm55MFJWVytSb0ltY0dBcmh4UnpvCnVnSVNUc05XeWxtWENCemxzQmVv
        Tkd0dkdLVnRqcTBEcElKM1VoNldXemsKLS0tIElXRGVKRXEwWVlMU281dmd0WkY4
        bmd1a2xCRE8zVG00RkM2TE03THBFbFEK+yZhWk/koY6MUpY2zfJmrp1xRz4I7+pN
        8rz+0EiHfTBulx0cP3RcPGM6pyjG1moFZ0DXENC779mukKAQBOztCw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2022-12-29T08:58:38Z"
  mac: ENC[AES256_GCM,data:yYLEb+TPn8JygHjwZ4onqigNoYKQsg1GMW3dxQSMLmWGmvx5shQqAEEhI2vjIicK95ZchoMXtazg4YzUiwyye//jgkJKOg7NMHBDv1DdBs08zBSol5dC6MI4bT7pez6LQOLCCf+h9BL9Wj8vXYNIPd2MQDCGeLHvV+EUVayoaZ8=,iv:2wxbNUJfG7wOtAu4IVTg35NL4zWssxLY12aryttjIQs=,tag:F9G5cqOfhFj/2WSKmAfTsQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
