apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform
  labels:
    app: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform
  template:
    metadata:
      labels:
        app: platform
    spec:
      containers:
        - name: platform
          image: morningnightguild/platform:v20221230165811
          imagePullPolicy: IfNotPresent
          env:
            - name: ENV
              value: "{{ .Values.env }}"
            - name: PORT
              value: "{{ .Values.port }}"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: platform-secret-database-url
                  key: DATABASE_URL
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform-secret-api-key
                  key: API_KEY
            - name: NEWRELIC_APP_NAME
              valueFrom:
                secretKeyRef:
                  name: platform-secret-newrelic-app-name
                  key: NEWRELIC_APP_NAME
            - name: NEWRELIC_LICENSE
              valueFrom:
                secretKeyRef:
                  name: platform-secret-newrelic-license
                  key: NEWRELIC_LICENSE
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
